### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by fosterc1** [cgkineo/adapt-navigationLogo#5]
Hello

Are there any plans to include the following options in this plugin:

- Ability to centre align logo
- Enable logo on menu only

Thanks

**Comment by kirsty-hames** [comment]
Hey @fosterc1, currently it is difficult to centre align due to nav items being floated. The following FW PR does include an API for the layout of nav items however which would accommodate this https://github.com/adaptlearning/adapt_framework/pull/2864

To enable a logo to display for menu or page view only, I would use the html `location-` classes to handle this in my theme css.
```
.location-page .navigation-logo {
  display: none;
}
```
